//
// Created by Administrator on 12/23/2024.
//

#ifndef SPRITESTATE_H
#define SPRITESTATE_H

enum SpriteState {
  SPRITE_STATE_IDLE,
  SPRITE_STATE_ACTIVE,
  SPRITE_STATE_TO_BE_REMOVED,

  SPRITE_STATE_ON_GROUND,
  SPRITE_STATE_JUMPING,
  SPRITE_STATE_FALLING,
  SPRITE_STATE_HIT,
  SPRITE_STATE_CROUCHED,

  SPRITE_STATE_DYING,

  SPRITE_STATE_INVULNERABLE,
  SPRITE_STATE_NOT_COLLIDABLE,
  SPRITE_STATE_INVISIBLE,
  SPRITE_STATE_NONE,
};

#endif // SPRITESTATE_H
